### PR TITLE
Dockerize

### PR DESCRIPTION
**Pull request by SHU-red**
- Added persist folder for mounting user-specific settings in docker
- Placed .dummy file in persist folder to be able to create "empty folder"
- Added .dummy to .gitignore
- Added variable to define path to possible autentification file in a central way
- Add os import and If/Else to check for auth file and execute command regarding to the availability of the auth file

ATTENTION:
1. My service is running at the moment, with this updated repo, then created a docker container for that (currently: "docker pull shur3d/ytmusicapi_microservice:experimental") and i can send requests to the container and get back a result
2. I have no idea how to check if authentication works, but it seems that this microservice is working for itsself

Feel free to change anything to a state you might like better

Thanks for your support

### CODE REVIEW

**Comment by fquirin** [comment]
Looks good :slightly_smiling_face: :+1: 
I'm assuming you've tested both cases (with and without auth.)? ^^

**Comment by SHU-red** [comment]
Sorry for the very late reply.

Without auth-file:

```
INFO:     Will watch for changes in these directories: ['/home/user/python-ytmusicapi-server']
INFO:     Uvicorn running on http://0.0.0.0:30010 (Press CTRL+C to quit)
INFO:     Started reloader process [1] using statreload
INFO:     Started server process [8]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
No authentication file found > Using YT without Auth
INFO:     192.168.178.20:38622 - "GET /search?q=Nevermind&maxResults=3 HTTP/1.1" 200 OK
INFO:     192.168.178.20:38622 - "GET /favicon.ico HTTP/1.1" 404 Not Found
```

With correclty named file "headers_auth.json" in folder persist

```
INFO:     Will watch for changes in these directories: ['/home/user/python-ytmusicapi-server']
INFO:     Uvicorn running on http://0.0.0.0:30010 (Press CTRL+C to quit)
INFO:     Started reloader process [1] using statreload
INFO:     Started server process [9]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
Found authentication file > Using YT-Auth ...
INFO:     192.168.178.20:38628 - "GET /search?q=Nevermind&maxResults=3 HTTP/1.1" 200 OK
```

Looks good to me, but i can't really proof that in my case my auth really works.
But in both cases i got correct feedback when checking:

`http://mysecretip:30010/search?q=Nevermind&maxResults=3`

**Comment by fquirin** [comment]
Merged, ty :partying_face:

**Comment by SHU-red** [comment]
Thanks for your support.

I updated the container to v0.3 including documentation.
https://hub.docker.com/r/shur3d/ytmusicapi_microservice

Feelin' strong :muscle::smiley:

**Comment by fquirin** [comment]
I've added the Docker URL to the README :slightly_smiling_face:

**Pull request merged**
